# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True, verbose_name='nascimento'),
        ),
    ]
